### PR TITLE
Updated Instruments.jl to work with Julia v1.0

### PR DESCRIPTION
**Pull request by bomber8013**
I updated the source code, ccalls, and the wrapper data types to be compatible with Julia v1.0. I have done some small scale bench testing with some instruments I have via USB and everything seems to work fine. The source code could use some polishing. And moving to a Julia native API down the road may be nice, similar to pyvisa-py that is a Python native PyVisa.

### CODE REVIEW

**Comment by catosp** [comment]
I tried to install Instruments but I recieved this error:
ERROR: Unsatisfiable requirements detected for package Instruments [98003276]:
 Instruments [98003276] log:
 ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

I tried with Julia 1.1, 1.0 and 0.7 and it give the same error. I don't know if is the right place to comment this but I don't know were call for help.
Thank you in advance!

**Comment by matthewware** [comment]
Try installing the master branch:
`(v1.0) pkg> add Instruments#master`
I'll try to clean things up a bit and cut a new release in the next few days.

**Comment by catosp** [comment]
I tried your method, but the following error appear:

┌ Error: Error building `Instruments`:
│ ERROR: LoadError: None of the selected providers can install dependency visa.
│ Use BinDeps.debug(package_name) to see available providers
│
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\Adrian\.julia\packages\BinDeps\ZEval\src\dependencies.jl:949
│  [3] satisfy!(::BinDeps.LibraryDependency) at C:\Users\Adrian\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [4] top-level scope at C:\Users\Adrian\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [5] include at .\boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:403
│  [9] top-level scope at none:0
│ in expression starting at C:\Users\Adrian\.julia\packages\Instruments\ggutG\deps\build.jl:6
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

**Comment by catosp** [comment]
I have visa installed in my computer (I use a python (pyVISA) program to communicate with my instruments and works very well).

**Comment by catosp** [comment]
if I run the following command:
`using Instruments`
then I have this error,even with visa64.dll installed in the system32 directory.

using Instruments
[ Info: Precompiling Instruments [2c6aeda0-45f5-11e9-10ba-f7b3d6416888]
ERROR: LoadError: LoadError: LoadError: Unable to load

libvisa (C:\Windows\System32\visa64.DLL)

Please re-run Pkg.build(package), and restart Julia.
Stacktrace:
 [1] error(::String, ::String) at .\error.jl:42
 [2] @checked_lib(::LineNumberNode, ::Module, ::Any, ::Any) at C:\Users\Adrian\.julia\packages\Instruments\ggutG\deps\deps.jl:11
 [3] include at .\boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1038
 [5] include at .\sysimg.jl:29 [inlined]
 [6] include(::String) at C:\Users\Adrian\.julia\packages\Instruments\ggutG\src\Instruments.jl:1
 [7] top-level scope at C:\Users\Adrian\.julia\packages\Instruments\ggutG\src\Instruments.jl:13
 [8] include at .\boot.jl:326 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1038
 [10] include(::Module, ::String) at .\sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:328 [inlined]
 [13] eval(::Expr) at .\client.jl:404
 [14] top-level scope at .\none:3
in expression starting at C:\Users\Adrian\.julia\packages\Instruments\ggutG\deps\deps.jl:20
in expression starting at C:\Users\Adrian\.julia\packages\Instruments\ggutG\deps\deps.jl:20
in expression starting at C:\Users\Adrian\.julia\packages\Instruments\ggutG\src\Instruments.jl:12
ERROR: Failed to precompile Instruments [2c6aeda0-45f5-11e9-10ba-f7b3d6416888] to C:\Users\Adrian\.julia\compiled\v1.1\Instruments\q3a94.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853

**Comment by matthewware** [comment]
You need to install the [NI VISA libraries](http://www.ni.com/visa/)
There a good chance you already have these if you're using pyVISA.  Check [here](https://pyvisa.readthedocs.io/en/master/getting_nivisa.html#getting-nivisa)
At the moment, Instruments.jl is configured for OSX -- see https://github.com/BBN-Q/Instruments.jl/blob/master/deps/build.jl  We could do some work to make this a little more universal.  Looks like you're on cygwin.  The build.jl script just needs to know where the visa shared library is on your machine.  Could you try pointing the build script to your copy?

**Comment by catosp** [comment]
I replaced the path to the shared library in the build.jl, the code is something like this:

using BinDeps
@BinDeps.setup
visa = library_dependency("visa", aliases = ["visa64","VISA","C:\\Windows\\System32"])
@BinDeps.install Dict(:visa=>:libvisa)

but i received the same error as before.

I also modified the path to the shared library in the .julia\packages\VISA, and when i tried to build, again the same error.

Capture

Maybe the C:\\Windows\\System32 is not the corect path to visa library?

**Comment by matthewware** [comment]
The path needs to be the path to the executable/shared library (I think).  So you might need "C:\Windows\System32\visa64.dll".

Could you also try building the package from the package manager?
`pkg> build Instruments` 
and post the out put?

**Comment by catosp** [comment]
Ok, i modified the path to C:\\Windows\\System32\\visa64.dll in Instruments and VISA and i obtain this error:
v1.1) pkg> build Instruments
  Building Instruments → `C:\Users\Adrian\.julia\packages\Instruments\ggutG\deps\build.log`
┌ Error: Error building `Instruments`:
│ ERROR: LoadError: None of the selected providers can install dependency visa.
│ Use BinDeps.debug(package_name) to see available providers
│
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\Adrian\.julia\packages\BinDeps\ZEval\src\dependencies.jl:949
│  [3] satisfy!(::BinDeps.LibraryDependency) at C:\Users\Adrian\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [4] top-level scope at C:\Users\Adrian\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [5] include at .\boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:403
│  [9] top-level scope at none:0
│ in expression starting at C:\Users\Adrian\.julia\packages\Instruments\ggutG\deps\build.jl:6
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

**Comment by matthewware** [comment]
Could this be a path issue since you're running inside of cygwin?  could the path be "/cygdrive/c/Windows..."

I'm also assuming your running on windows with cygwin?  Is this a custom build of julia?

**Comment by catosp** [comment]
This director C:\cygwin\home\Administrator\ does not exist in my computer, i don't know why appear in this error. Is not a custom build of julia, I just downloaded from the official website.

**Comment by matthewware** [comment]
Can you install the official release outside of cygwin? -> https://julialang-s3.julialang.org/bin/winnt/x64/1.1/julia-1.1.0-win64.exe  I just tested the master branch on a windows machine with out issues.

**Comment by gribeill** [comment]
Hi @catosp -- I've updated to code to use the `pyvisa-py` backend instead of the NI backend, which hopefully should be a little more cross-platform friendly. You can give it a try here: 0cc9fad1ba7a191ecd3679a5a850878f5dfeedc8 . Hopefully this will help fix some of your path problems as `Conda.jl` *should* download everything automatically...

**Comment by catosp** [comment]
I tried on my home computer:
I installed the julia version that you give me, then i installed the Instruments#master and works beautifully!!!!!
You are the best guys!!!!
Tomorrow I will try to do the same steps on my lab computer.
Thank you very much!

**Comment by matthewware** [comment]
Turns out I was confused by the cygwin.  I think the Windows builds are done on cygwin -- hence the file path you were seeing.  I'm still not entirely sure what you're seeing but I think we're getting there.

**Pull request merged**
